import "./globals.css";

import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {ReactNode} from "react";

import Providers from "@/components/Providers";

const inter = Inter({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700", "900"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
	      <Providers>
		      {children}
	      </Providers>
      </body>
    </html>
  );
}
